name: dev-deploy

on:
  push:
    branches:
      - dev

jobs:
  trigger-source:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Dev Workflow
        env:
          pat: ${{ secrets.ACTIONS_KEY }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $pat" \
          https://api.github.com/repos/uenot/tobyuenodotcom-dev/dispatches \
          -d '{"event_type":"deploy"}'
          


