name: Deploy Dev to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Elm
        uses: jfairbank/setup-elm@v1
        with:
          elm-version: '0.19.1'

      - name: Install dependencies
        run: elm make

      - name: Build the project
        run: elm make src/Main.elm --output=dist/main.js

      - name: Create CNAME file
        run: echo "dev.tobyueno.com" > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: dev.tobyueno.com
