name: dev-deploy

on:
  push:
    branches:
      - dev

jobs:
  trigger-source:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch-dev
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: uenot
          repo: tobyuenodotcom-dev
          github_token: ${{ secrets.ACTIONS_KEY }}
