name: prod-deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-downstream:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch-prod
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: uenot
          repo: tobyuenodotcom-prod
          github_token: ${{ secrets.ACTIONS_KEY }}
          workflow_file_name: deploy.yml
